// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "tsx ./src/utils/seed.ts",
    path: "prisma/migrations",
  },
  datasource: {
    url: import.meta.env.DATABASE_URL,
  },
});
